N_ROWS = 7
N_COLS = 11
N_ELEMENTS = N_ROWS * N_COLS
CLICK_ACTION = N_ELEMENTS
MAX_STEPS = 25
MAX_ACTIONS = N_ELEMENTS+1
TUPLE_SIZE = 9

COLOR_LIST = ["BLUE", "GREEN", "YELLOW", "RED", "PURPLE"]
SIZE_LIST = [0.8, 1.6, 2.8]
SHAPE_LIST = ["CIRCLE", "SEMI-CIRCLE", "SQUARE", "TRIANGLE", "CROSS"]

FEATURE_COLOUR = "colour"
FEATURE_SHAPE = "shape"
FEATURE_SIZE = "size"
FEATURE_TEXT = "text"

COLOUR_BONUS = 5
SIZE_BONUS = 12
SHAPE_BONUS = 21
TEXT_BONUS = 21
COLOUR_PENALTY = 0.11
SIZE_PENALTY = 0.0825
SHAPE_PENALTY = 0.04125
