N_ROWS = 7
N_COLS = 11
COLOR_LIST = ["BLUE", "GREEN", "YELLOW", "RED", "PURPLE"]
SIZE_LIST = [0.8, 1.6, 2.8]
SHAPE_LIST = ["CIRCLE", "SEMI-CIRCLE", "SQUARE", "TRIANGLE", "CROSS"]

FEATURE_COLOUR = "colour"
FEATURE_SHAPE = "shape"
FEATURE_SIZE = "size"
FEATURE_TEXT = "text"